#!/usr/bin/env python3
"""Split zodiac sheets into transparent PNGs and emit JS data modules.

Packs (source sheets are not committed — keep them locally to re-extract):
  glyph — 42Z_zodiac8.jpg → assets/signs + src/data/sign-icons.js
  line  — 5561119.jpg     → assets/signs-line + src/data/sign-icons-line.js

Licenses:
  docs/license-zodiac-white-signs-set-67006418.pdf
  docs/license-flat-zodiac-sign-collection-15112717.pdf

Usage:
  python scripts/extract-zodiac-signs.py           # all packs
  python scripts/extract-zodiac-signs.py glyph
"""

from __future__ import annotations

import base64
import json
import sys
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SIZE = 256

WESTERN = [
    "aries",
    "taurus",
    "gemini",
    "cancer",
    "leo",
    "virgo",
    "libra",
    "scorpio",
    "sagittarius",
    "capricorn",
    "aquarius",
    "pisces",
]


def write_pack(out_dir: Path, js_out: Path, images: dict[str, Image.Image], tag: str) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    icons: dict[str, str] = {}
    for name, img in images.items():
        path = out_dir / f"{name}.png"
        img.save(path, optimize=True)
        b64 = base64.b64encode(path.read_bytes()).decode("ascii")
        icons[name] = f"data:image/png;base64,{b64}"
        print(f"  {name}: {path.relative_to(ROOT)} ({path.stat().st_size} bytes)")

    js_out.parent.mkdir(parents=True, exist_ok=True)
    js_out.write_text(
        f"/** Auto-generated by scripts/extract-zodiac-signs.py ({tag}) — do not edit. */\n"
        f"export default {json.dumps(icons, indent=2)};\n",
        encoding="utf-8",
    )
    print(f"  wrote {js_out.relative_to(ROOT)}")


def to_square(rgba: Image.Image, size: int = SIZE, margin: float = 0.06) -> Image.Image:
    w, h = rgba.size
    side = max(w, h)
    pad = int(side * margin)
    canvas = Image.new("RGBA", (side + pad * 2, side + pad * 2), (0, 0, 0, 0))
    canvas.paste(rgba, (pad + (side - w) // 2, pad + (side - h) // 2), rgba)
    return canvas.resize((size, size), Image.Resampling.LANCZOS)


def white_line_to_transparent(rgb: Image.Image, floor: int = 40, span: int = 80) -> Image.Image:
    a = np.array(rgb.convert("RGB"))
    br = a.mean(axis=2)
    alpha = np.clip((br - floor) * (255 / span), 0, 255).astype(np.uint8)
    rgba = np.zeros((a.shape[0], a.shape[1], 4), dtype=np.uint8)
    rgba[..., 0] = 255
    rgba[..., 1] = 255
    rgba[..., 2] = 255
    rgba[..., 3] = alpha
    return Image.fromarray(rgba, "RGBA")


def tight_on_mask(mask: np.ndarray, pad: int = 24):
    ys, xs = np.where(mask)
    if len(xs) == 0:
        return 0, 0, mask.shape[1], mask.shape[0]
    return (
        max(0, int(xs.min()) - pad),
        max(0, int(ys.min()) - pad),
        min(mask.shape[1], int(xs.max()) + 1 + pad),
        min(mask.shape[0], int(ys.max()) + 1 + pad),
    )


# ── glyph (42Z banner) ──────────────────────────────────────────────

GLYPH_REGIONS = {
    "aries": (1850, 650, 2750, 1450),
    "taurus": (3100, 700, 3950, 1480),
    "gemini": (4450, 650, 5100, 1380),
    "cancer": (5550, 650, 6400, 1350),
    "leo": (6900, 520, 7600, 1400),
    "virgo": (400, 1750, 1300, 2500),
    "libra": (1500, 1700, 2400, 2500),
    "scorpio": (2400, 1700, 3400, 2500),
    "sagittarius": (3600, 1680, 4400, 2480),
    "capricorn": (4550, 1680, 5500, 2500),
    "aquarius": (5700, 1750, 6650, 2350),
    "pisces": (6900, 1680, 7650, 2500),
}


def extract_glyph() -> None:
    print("pack: glyph")
    source = ROOT / "42Z_zodiac8.jpg"
    if not source.exists():
        raise SystemExit(f"Missing {source.name}")
    im = Image.open(source).convert("RGB")
    bright = np.array(im).mean(axis=2)
    images: dict[str, Image.Image] = {}
    for name, (x0, y0, x1, y1) in GLYPH_REGIONS.items():
        sub = bright[y0:y1, x0:x1] > 55
        tx0, ty0, tx1, ty1 = tight_on_mask(sub, pad=40)
        crop = im.crop((x0 + tx0, y0 + ty0, x0 + tx1, y0 + ty1))
        images[name] = to_square(white_line_to_transparent(crop))
    write_pack(
        ROOT / "assets" / "signs",
        ROOT / "src" / "data" / "sign-icons.js",
        images,
        "glyph",
    )


# ── line (5561119 3×4 grid, labels stripped) ────────────────────────

def extract_line() -> None:
    print("pack: line")
    source = ROOT / "5561119.jpg"
    if not source.exists():
        raise SystemExit(f"Missing {source.name}")
    im = Image.open(source).convert("RGB")
    bright = np.array(im).mean(axis=2)
    W, H = im.size
    cw, ch = W // 4, H // 3
    images: dict[str, Image.Image] = {}

    for i, name in enumerate(WESTERN):
        r, c = divmod(i, 4)
        x0, y0 = c * cw, r * ch
        # Labels sit in the bottom ~24% — ignore that strip entirely.
        y_icon_end = int(ch * 0.76)
        sub = bright[y0 : y0 + y_icon_end, x0 : x0 + cw]
        dens = (sub > 80).mean(axis=1)
        bands = []
        start = None
        for y, on in enumerate(dens > 0.012):
            if on and start is None:
                start = y
            elif not on and start is not None:
                bands.append((start, y - 1))
                start = None
        if start is not None:
            bands.append((start, y_icon_end - 1))
        # Drop trailing label crumbs still inside the strip.
        label_zone = int(y_icon_end * 0.88)
        bands = [b for b in bands if b[1] - b[0] >= 8 and b[0] < label_zone]
        if not bands:
            mask = sub > 80
        else:
            main = max(bands, key=lambda b: b[1] - b[0])
            kept = [b for b in bands if b[0] <= main[1] + 40]
            iy0 = min(b[0] for b in kept)
            iy1 = max(b[1] for b in kept)
            mask = np.zeros_like(sub, dtype=bool)
            mask[iy0 : iy1 + 1] = sub[iy0 : iy1 + 1] > 80
        tx0, ty0, tx1, ty1 = tight_on_mask(mask, pad=20)
        crop = im.crop((x0 + tx0, y0 + ty0, x0 + tx1, y0 + ty1))
        images[name] = to_square(white_line_to_transparent(crop, floor=50, span=70))

    write_pack(
        ROOT / "assets" / "signs-line",
        ROOT / "src" / "data" / "sign-icons-line.js",
        images,
        "line",
    )


PACKS = {
    "glyph": extract_glyph,
    "line": extract_line,
}


def main() -> None:
    wanted = sys.argv[1:] or list(PACKS)
    unknown = [p for p in wanted if p not in PACKS]
    if unknown:
        raise SystemExit(f"Unknown pack(s): {unknown}. Choose from {list(PACKS)}")
    for name in wanted:
        PACKS[name]()
    for tmp in (
        ROOT / "scripts" / "out" / "line_test",
        ROOT / "scripts" / "out" / "line_fix",
        ROOT / "assets" / "signs" / "_preview",
    ):
        if tmp.exists() and tmp.is_dir():
            for f in tmp.glob("*"):
                f.unlink()
            tmp.rmdir()
            print(f"cleaned {tmp.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
